# Generated by Django 6.0.3 on 2026-04-05 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('board_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rssi', models.IntegerField(help_text='WiFi signal strength')),
                ('sensor_data', models.JSONField(help_text='JSON object containing sensor readings (water_temp, air_temp, air_humidity, water_overflow, water_dry)')),
                ('relay_status', models.JSONField(help_text='JSON object containing relay states (relay1_pump, relay2_fan, relay3_heater)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_logs', to='myapp.device')),
            ],
            options={
                'verbose_name': 'Telemetry Log',
                'verbose_name_plural': 'Telemetry Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='myapp_telem_created_985d14_idx'), models.Index(fields=['device', '-created_at'], name='myapp_telem_device__a01b8a_idx')],
            },
        ),
    ]
