# Generated by Django 6.0.3 on 2026-04-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(default='broker.hivemq.com', help_text='MQTT Broker hostname or IP address', max_length=255)),
                ('port', models.IntegerField(default=1883, help_text='MQTT Broker port (default: 1883 for TCP, 8883 for SSL)')),
                ('username', models.CharField(blank=True, help_text='MQTT username (leave empty if not required)', max_length=100, null=True)),
                ('password', models.CharField(blank=True, help_text='MQTT password (leave empty if not required)', max_length=100, null=True)),
                ('telemetry_topic', models.CharField(default='smartfarm/+/telemetry', help_text='Topic pattern for receiving telemetry data (use + as wildcard)', max_length=255)),
                ('status_topic', models.CharField(default='smartfarm/+/status', help_text='Topic pattern for receiving device status (use + as wildcard)', max_length=255)),
                ('control_topic_pattern', models.CharField(default='smartfarm/{board_id}/control', help_text='Topic pattern for sending control commands (use {board_id} as placeholder)', max_length=255)),
                ('keepalive', models.IntegerField(default=60, help_text='Keepalive interval in seconds')),
                ('qos', models.IntegerField(choices=[(0, 'QoS 0 - At most once'), (1, 'QoS 1 - At least once'), (2, 'QoS 2 - Exactly once')], default=0, help_text='Quality of Service level for subscriptions')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MQTT Setting',
                'verbose_name_plural': 'MQTT Settings',
            },
        ),
        migrations.CreateModel(
            name='RelayTestPanel',
            fields=[
            ],
            options={
                'verbose_name': 'Relay Test Panel',
                'verbose_name_plural': 'Relay Test Panel',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.device',),
        ),
    ]
