# Generated by Django 6.0.3 on 2026-04-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mqttsettings_relaytestpanel'),
    ]

    operations = [
        migrations.CreateModel(
            name='N8NSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_outbound_webhook', models.BooleanField(default=False, help_text='Send relay command events from Dashboard/Admin to n8n webhook')),
                ('outbound_webhook_url', models.URLField(blank=True, help_text='n8n webhook URL for receiving relay command events', null=True)),
                ('enable_inbound_webhook', models.BooleanField(default=False, help_text='Allow n8n to call Dashboard API for relay control')),
                ('inbound_auth_token', models.CharField(blank=True, default='', help_text='Token for authenticating inbound n8n webhook requests', max_length=128)),
                ('request_timeout_seconds', models.IntegerField(default=10, help_text='HTTP timeout for outbound webhook requests (seconds)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'N8N Setting',
                'verbose_name_plural': 'N8N Settings',
            },
        ),
    ]
