# Generated by Django 6.0.3 on 2026-04-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_n8nsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='n8nsettings',
            name='device_status_webhook_url',
            field=models.URLField(blank=True, help_text='n8n webhook URL for receiving device status events', null=True),
        ),
        migrations.AddField(
            model_name='n8nsettings',
            name='enable_device_status_webhook',
            field=models.BooleanField(default=False, help_text='Send device online/offline status updates to n8n webhook'),
        ),
        migrations.AddField(
            model_name='n8nsettings',
            name='enable_telemetry_webhook',
            field=models.BooleanField(default=False, help_text='Send telemetry data from ESP32 devices to n8n webhook'),
        ),
        migrations.AddField(
            model_name='n8nsettings',
            name='telemetry_webhook_url',
            field=models.URLField(blank=True, help_text='n8n webhook URL for receiving telemetry events', null=True),
        ),
    ]
